# Generated by Django 3.1.7 on 2021-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210424_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='bot_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
