# Generated by Django 3.1.7 on 2021-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_filial_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_callcenter',
            field=models.BooleanField(default=False),
        ),
    ]
