# Generated by Django 3.1.7 on 2021-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_callcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='chat_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
