# Generated by Django 3.1.7 on 2021-04-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210424_0959'),
        ('buyurtma', '0002_books_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.filial'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.filial'),
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
