# Generated by Django 3.1.7 on 2021-06-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0005_auto_20210612_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='meals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
