# Generated by Django 3.1.7 on 2021-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0007_books_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
