# Generated by Django 3.1.7 on 2021-06-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0008_books_where'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='where',
        ),
    ]
