# Generated by Django 3.1.7 on 2021-06-22 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_filial_chat_id'),
        ('buyurtma', '0009_remove_books_where'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bor_yoqligi', models.CharField(choices=[('1', 'bor'), ('2', 'yoq')], max_length=255)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.filial')),
            ],
        ),
    ]
