# Generated by Django 3.1.7 on 2021-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0010_maxsulotlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulotlar',
            name='izoh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
