# Generated by Django 3.1.7 on 2022-01-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0011_maxsulotlar_izoh'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
