# Generated by Django 3.1.7 on 2022-01-22 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0012_auto_20220112_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='buyurtma.rooms'),
        ),
    ]
