# Generated by Django 3.1.7 on 2022-01-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0013_auto_20220122_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_to',
            field=models.DateTimeField(null=True),
        ),
    ]
