# Generated by Django 3.1.7 on 2021-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtors',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
