# Generated by Django 3.1.7 on 2021-04-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Oylik', 'Oylik'), ('Yillik', 'Yillik')], default='Oy', max_length=25)),
                ('savdo', models.IntegerField(default=0)),
                ('mijoz_soni', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('oy', models.IntegerField(default=0)),
                ('yil', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
