# Generated by Django 3.1.7 on 2021-04-23 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'verbose_name_plural': 'Tuman',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('finishedPrice', models.IntegerField(default=0)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, "Boshlang'ich"), (1, 'Muhokamada'), (2, 'Qaror qabul qilish'), (3, 'Shartnoma'), (4, "Yo'qotish"), (5, 'Muvaffaqqiyatli yakunlash'), (6, 'Promouter')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finishedDate', models.DateTimeField(blank=True, null=True)),
                ('degree', models.IntegerField(choices=[(1, 'Past'), (2, 'O`rta'), (3, 'Yuqori')], default=1)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('abcxyz', models.CharField(max_length=255, null=True)),
                ('step1', models.TextField(blank=True, default='-', null=True)),
                ('step2', models.TextField(blank=True, default='-', null=True)),
                ('step3', models.TextField(blank=True, default='-', null=True)),
                ('step4', models.TextField(blank=True, default='-', null=True)),
                ('step5', models.TextField(blank=True, default='-', null=True)),
                ('status_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('debt', models.IntegerField(default=0)),
                ('joinBy', models.IntegerField(choices=[(0, 'Odatiy'), (1, 'Telegram orqali')], default=0)),
                ('tg_chatid', models.IntegerField(default=0)),
                ('categoryproduct', models.ManyToManyField(blank=True, to='board.CategoryProduct')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.district')),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('step', models.IntegerField(choices=[(0, 'Start'), (1, 'Contact'), (2, 'Name'), (3, 'Company'), (4, 'Company Address'), (5, 'Finished')], default=1)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('status', models.IntegerField(choices=[(0, "Ro'yxatga olindi"), (1, 'Bajarilmoqda'), (2, 'Bajarildi'), (3, "O'chirildi")], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finishedDate', models.DateTimeField(null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'verbose_name_plural': 'Viloyat',
            },
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Lead yaratildi'), (1, 'Lead taxrirlandi'), (2, "Status o'zgardi"), (3, "Izoh qo'shildi")], default=0)),
                ('oldStatus', models.IntegerField(default=0)),
                ('newStatus', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('color', models.CharField(default='primary', max_length=255)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.lead')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.region'),
        ),
    ]
