# Generated by Django 3.1.7 on 2021-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='where',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
