from django.urls import path
from .views import *

urlpatterns = [
    path('rooms/', Room.as_view(), name='rooms'),
    path('buyurtmaolish/', BuyurtmaOlish.as_view(), name='buyurtmaolish'),
    path('buyurtmaolishfil/', BuyurtmaOlishFil.as_view(), name='buyurtmaolishfil'),
    path('book/', Book.as_view(), name='book'),
    path('products/', Products.as_view(), name='products'),
    path('etirozcall/', EtirozCall.as_view(), name='etirozcall'),
    path('calendar/', Calendar.as_view(), name='calendar'),
    path('calendarfil/', CalendarFil.as_view(), name='calendarfil'),
    path('bookrange/', BookRange, name='bookrange'),
    path('olib-ketish/', OlibKetish, name='olib-ketish'),
    path('yetkazib-berish/', YetkazibBerish, name='yetkazib-berish'),
    path('band-qilish/', BandQilish, name='band-qilish'),
    path('', Aktiv.as_view(), name='aktiv'),
    path('app-calendarcall/', CalenAppCall.as_view(), name='app-calendarcall'),
    path('smsfilial/', SmsFilial.as_view(), name='smsfilial'),
    path('clients/', Clients.as_view(), name='clients'),
    path('smscall/', SmsCall.as_view(), name='smscall'),
    path('change/', Change, name='change'),
    path('getxona/', GetXona, name='getxona'),
    path('getxonalar/', GetXonalar, name='getxonalar'),
    path('getbuyurtmalar/', GetBuyurtmalar, name='getbuyurtmalar'),
    path('getuser/', GetUser, name='getuser'),
    path('smsgatewayf/', SmsGatewayF, name='smsgatewayf'),
    path('delete/', BookDelete, name='delete'),
    path('test/', check_book, name='test'),
    path('changeroom1/', changeroom1, name='changeroom1'),
    path('changeroom0/', changeroom0, name='changeroom0'),
    path("task1", TaskClass1.as_view(), name="taskUrl1"),
    path("task", TaskClass.as_view(), name="taskUrl"),
    path("create_task/", create_task),
    path("change_task_status/", change_task_status),
    path("note_task/", note_task),
    path('debt1/', Debt1.as_view(), name='debt1'),
    path('debt/', Debt.as_view(), name='debt'),
    path('debthistory/', DebtHistory, name='debthistory'),
    path('adddebt/', AddDebt, name='adddebt'),
    path('adddebtor/', AddDebtor, name='adddebtor'),
    path('getbuyurtma/', getbuyurtma, name='getbuyurtma'),
    path('getbuyurtma1/', getbuyurtma1, name='getbuyurtma1'),
    path('editbuyurtma/', editbuyurtma, name='editbuyurtma'),
    path('editbuyurtma1/', editbuyurtma1, name='editbuyurtma1'),
    path('getmaxsulot/', getmaxsulot, name='getmaxsulot'),
    path('changemaxsulot/', changemaxsulot, name='changemaxsulot'),
    path('addmaxsulot/', addmaxsulot, name='addmaxsulot'),
]
